### ISSUE TITLE
SMTPKitten will sometimes get stuck

### ISSUE THREAD

**Issue by thoven87** [Joannis/SMTPKitten#17]
**Describe the bug**
I have a job using [swift jobs](https://github.com/hummingbird-project/swift-jobs-redis) after a while the jobs will get stuck in processing state.

**To Reproduce**
Sample code that reproduces the issue. https://github.com/thoven87/swift-job-stuck/tree/main

**Expected behavior**
I would expect the emails to be sent all the time except when there's network failure instead of just not responding sometimes.

**Details:**
- OS: [macOS 14, Ubuntu 22.04]
- Release 0.2.0
- SMTP Server Mailtrap, Resend

**Additional context**

**Comment by Joannis** [comment]
Should be addressed alraedy by #14

**Comment by thoven87** [comment]
Closing this issue as 1.0.0-alpha-1 was released.
