### ISSUE TITLE
HTML showing as plain text in microsoft email services.

### ISSUE THREAD

**Issue by jcbriones** [Joannis/SMTPKitten#2]
Every time I send out email as html as the content type, the email is showing as plain text if the receiver has an outlook, live or hotmail domains. Or basically anything microsoft hosted domains (included business emails that uses office365)

**Comment by DamonHu** [comment]
remove the  code of  36 line in `SMTPClientOutboundHandler` file

```
// headersText += "Content-Type: text/plain; charset=\"utf-8\"\r\n"
```
