### ISSUE TITLE
VaporSMTPKit Does Not Load

### ISSUE THREAD

**Issue by felswa** [Joannis/SMTPKitten#7]
Hi. When I try to load VaporSMTPKit which depends on SMTPKitten I am now getting the following error:

when I now update the package I get the following errors

SMTPClient has no member flatMap
Generic parameter T could not be inferred in sent = mails.
in:

return SMTPClient.connect(
hostname: credentials.hostname,
port: credentials.port,
ssl: credentials.ssl,
eventLoop: self.eventLoopGroup.next()
).flatMap { client in
client.login(
user: credentials.email,
password: credentials.password
).flatMap {
let sent = mails.map(client.sendMail)
return EventLoopFuture.andAllSucceed(sent, on: self.eventLoopGroup.next())
}
}

**Comment by Joannis** [comment]
Closing because SMTPKitten will get 1.0 soon, and this API will not exist in this shape anymore
